config/routes.rb
Rails.application.routes.draw do
  

      devise_for :admin, skip: [:registrations, :password], controllers: {
        sessions: 'admin/sessions'
      }
      namespace :admin do
        get 'dashboards', to: 'dashboards#index'
        resources :users, only: [:destroy]
      end

      devise_scope :user do
        post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
      end

      devise_for :users, controllers:{
        registrations: "users/registrations"
      }
      # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

      scope module: :public do
        root to: "homes#top"
        get "about", to: "homes#about"
      
        resources :users, only: [:show] do 
          member do
            get :following
            get :followers
          end
        end

        get "search", to: "searches#search"
      
        resources :posts, only: [:index, :show, :new, :edit, :create, :destroy, :update] do
          resources :post_comments, only: [:create, :destroy, :edit, :update]
          resources :favorites, only: [:create, :destroy]
        end

        resources :relationships, only: [:create, :destroy]

      end
      

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  devise authentication_keys: [:email]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 200 }

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts,dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end



    has_many :active_relationships,
    class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy


    has_many :passive_relationships,
    class_name: "Relationship",
    foreign_key: "followed_id",
    dependent: :destroy


    has_many :following, through: :active_relationships, source: :followed


    has_many :followers, through: :passive_relationships, source: :follower

    def follow(user)
    following << user unless self == user
    end

    def unfollow(user)
    following.destroy(user)
    end

    def following?(user)
    following.include?(user)
    end

    validates :bio, length: { maximum: 160 }, allow_blank: true


    def favorited?(post)
      favorites.exists?(post_id: post.id)
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication

  helper_method :guest_user?

  def guest_user?
    user_signed_in? && current_user.email == "guest@example.com"
  end

  def reject_guest!
    return unless guest_user?
    redirect_to root_path, alert: "ゲストユーザーは閲覧専用です"
  end

  before_action :configure_permitted_parameters,
   if: :devise_controller?
    before_action :configure_authentication
 
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :bio])

    devise_parameter_sanitizer.permit(:account_update,keys:[:name, :bio])
  end
 
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
 
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
 
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.includes(:user) .order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post,notice: "投稿しました"
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post =current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post,notice: "更新しました"
    else
      render :edit
    end
  end
  
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path,notice: "削除しました"
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :is_public)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "退会しました"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    redirect_to root_path, alert:"権限がありません" unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <%= link_to "マッスルメモリー", posts_path, class: "navbar-brand fw-bold" %>

    <div class="d-flex gap-2">
      <% if user_signed_in? %>
        <%= link_to "Top", posts_path, class: "btn btn-outline-secondary" %>
        <%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
        <%= link_to "マイページ", user_path(current_user), class: "btn btn-outline-secondary" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, method: :post, class: "btn btn-outline-primary" %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Muscle</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muscle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/52b3005dcd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <title>Muscle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container-main">
  <% flash.each do |type, message| %>
    <% bs_class =
      case type.to_s
      when "notice" then "alert-success"
      when "alert"  then "alert-danger"
      else "alert-info"
      end
    %>

    <div class="alert <%= bs_class %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
      <%= yield %>
    </div>
  </body>
  </head>

</html>